services:
  app:
    image: 333-backend
    container_name: app_backend
    ports:
      - "8000:8000"
    networks:
      - app_network

  mysql:
    image: mysql/mysql-server
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=app_db
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
    ports:
      - "3306:3306"
    networks:
      - app_network


networks:
  app_network:
    driver: bridge
